name: Terraform Deploy VM to GCP

on:
  push:
    branches: main 

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Create credentials file from secret
        run: |
           echo '${{ secrets.GCP_CREDENTIALS }}' > gcp-creds.json
           export GOOGLE_APPLICATION_CREDENTIALS=${{ github.workspace }}/gcp-creds.json
        shell: bash

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Plan
        run: |
          terraform plan -var="credentials_file=${{ github.workspace }}/gcp-creds.json"
        working-directory: terraform

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve -var="credentials_file=${{ github.workspace }}/gcp-creds.json"
        working-directory: terraform
